---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
channels:
  - conda-forge
  - bioconda
dependencies:
  - bioconda::umi_tools=1.1.5
  - python=3.9.18
  - matplotlib=3.8.2
  - scipy=1.12.0
  - regex=2023.12.25
  - numpy=1.26.4
  - pandas=2.2.0
  - pysam=0.22.0
  - future=0.18.3
  - pybktree=1.1
